### ISSUE TITLE
[Crash] Crash when you shift crafting something in 2x2 grid.

### ISSUE THREAD

**Issue by murao-kun** [baguchan/Smooth-Swapping-Forge#3]
[crash-2022-11-13_15.37.20-client.txt](https://github.com/baguchan/Smooth-Swapping-Forge/files/9997667/crash-2022-11-13_15.37.20-client.txt)

**Comment by BugmanBugman** [comment]
Got this as well

**Comment by RDP8** [comment]
Same here.
